services:
  backend:
    build: ./Backend

    volumes:
      - ./Backend:/app  
      - backend_venv:/app/venv 
      - models:/app/models  

    environment:
      - HF_HOME=/app/
      - MODEL_DIR="/app/models"
      - DATABASE_URL=postgresql://myuser:mypassword@database:5432/mydatabase
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy  
    command: ["/app/venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:  
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase"]
      interval: 5s
      retries: 5

  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend:/app  
      - frontend_node_modules:/app/node_modules  
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host", "--port", "3000"]

volumes:
  pgdata:
  backend_venv:
  models:
  frontend_node_modules:



